#+POSTID: 1761
#+BLOG: perlancar
#+CATEGORY: perl,cli
#+TAGS: perl,cli
#+DESCRIPTION:
#+TITLE: Removing password from PDF files

Electronic billing statement is great. Paperless, easier to archive, and you
don't need to care if you leave the house for a month or move addresses. But
what's the most irritating thing about credit card e-statements? That the banks
decide to encrypt the PDF with some easy-to-guess password like YYYYMMDD of your
birth date, or FirstNameDDMMYY, or some other variation. But each bank picks a
different password, naturally.

So the first thing I do after downloading an e-statement is to run them through
my [[https://metacpan.org/pod/remove-pdf-password][remove-pdf-password]] script. It's basically a wrapper for "qpdf" and will try
a series of passwords, then decrypt the PDF in-place. You put the passwords in
~/.config/remove-pdf-password.conf, e.g.:

: passwords = PASS1  ; anz
: passwords = PASS2  ; hsbc
: passwords = PASS2  ; uob
: ...

The script is distributed with the [[https://metacpan.org/pod/App::PDFUtils][App::PDFUtils]] distribution. There's the
counterpart script in the distribution, [[https://metacpan.org/pod/add-pdf-password][add-pdf-password]], in case you want to
return the favor. The next time some bank staff requests your documents, you can
send them in an email encrypted. In the email you write, "the password is the
name of the bank followed by the phone number of the bank, but replace every f
with f*ckyou ..."
